runner:
    verible-lint:
        cmd: 'verible-verilog-lint $(find -L . -type f -name *.v) | cat'
        errorformat:
            - '%f:%l:%c: %m'

    verible-syntax:
        cmd: 'verible-verilog-syntax $(find -L . -type f -name *.v)'
        errorformat:
            - '%f:%l:%c: %m'
